// generated by Proto2Typescript. do not touch!

declare module defaultProto {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		MLoginReq: MLoginReqBuilder;
		MLoginRet: MLoginRetBuilder;
		
	}
}

declare module defaultProto {

	export interface MLoginReq extends ProtoBufModel {
		username: string;
		getUsername() : string;
		setUsername(username : string): void;
		password: string;
		getPassword() : string;
		setPassword(password : string): void;
		
	}
	
	export interface MLoginReqBuilder {
		new(): MLoginReq;
		decode(buffer: ArrayBuffer) : MLoginReq;
		//decode(buffer: NodeBuffer) : MLoginReq;
		//decode(buffer: ByteArrayBuffer) : MLoginReq;
		decode64(buffer: string) : MLoginReq;
		
	}	
}

declare module defaultProto {

	export interface MLoginRet extends ProtoBufModel {
		userid: number;
		getUserid() : number;
		setUserid(userid : number): void;
		username: string;
		getUsername() : string;
		setUsername(username : string): void;
		hashcode: string;
		getHashcode() : string;
		setHashcode(hashcode : string): void;
		
	}
	
	export interface MLoginRetBuilder {
		new(): MLoginRet;
		decode(buffer: ArrayBuffer) : MLoginRet;
		//decode(buffer: NodeBuffer) : MLoginRet;
		//decode(buffer: ByteArrayBuffer) : MLoginRet;
		decode64(buffer: string) : MLoginRet;
		
	}	
}
